= Untangled Developer's Reference
:source-highlighter: coderay
:source-language: clojure
:toc:
:toc-placement: left
:toclevels: 3
:sectlinks:
:sectanchors:
:sectnums:

== Introduction

This reference guide is meant to be an indexed document for quickly finding information about the Untangled Web
Framework. If you're trying to learn Untangled, then you should read and do the exercises in the 
https://github.com/untangled-web/untangled-devguide[developer's guide].

== Untangled Client

include::https://raw.githubusercontent.com/untangled-web/untangled-client/develop/docs/index.adoc[lines=23..-1, leveloffset=+1]

== Untangled Server and Fetching Data

include::https://raw.githubusercontent.com/untangled-web/untangled-server/develop/docs/index.adoc[lines=23..-1, leveloffset=+1]

== Untangled Spec

include::https://raw.githubusercontent.com/untangled-web/untangled-spec/develop/docs/index.adoc[lines=23..-1, leveloffset=+1]

== Untangled Datomic

include::https://raw.githubusercontent.com/untangled-web/untangled-datomic/develop/docs/index.adoc[lines=23..-1, leveloffset=+1]

== Websockets

The Untangled Websockets library gives you an alternate network implementation (for client and server) that maintains
a persistent TCP connection and enables server push. Note that the server continues to support the non-websocket API
endpoint, which is useful if you want to have multiple client types supported by the same server.

== Internationalization

Untangled client comes with tools to enable full internationalization based on GNU gettext. The main features include:

- Use your native language (e.g. English) as the real strings in the UI. These will also act as the default values
  should a translation be missing
- Support for date, time, numeric, and plural formatting.
- Support for splitting compiled translations into dynamically loadable modules.
